# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-01-19 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0002_auto_20190119_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='pages',
            field=models.TextField(blank=True, verbose_name='동아리 페이스북/유튜브 페이지 주소'),
        ),
        migrations.AlterField(
            model_name='club',
            name='video_url1',
            field=models.CharField(blank=True, max_length=63, verbose_name='동아리 소개 비디오 주소 #1'),
        ),
        migrations.AlterField(
            model_name='club',
            name='video_url2',
            field=models.CharField(blank=True, max_length=63, verbose_name='동아리 소개 비디오 주소 #2'),
        ),
    ]
